[package]
name = "dex_challenge"
version = "0.1.0"
edition = "2023_11"

[dependencies]
starknet = "2.11.4"
openzeppelin = { git = "https://github.com/OpenZeppelin/cairo-contracts.git", tag = "v0.17.0" }

[[target.starknet-contract]]
